name=digitalWriteFast
version=1.4.0
author=
maintainer=
sentence=Fork from ArminJo. Fast pin access for AVR microcontrollers
paragraph=Provides functions digitalWriteFast(), pinModeFast(), digitalReadFast(pinNum) and digitalToggleFast().
category=Other
url=https://github.com/emagnetto/digitalWriteFast
architectures=*
includes=digitalWriteFast.h
